server:
  port: "${SERVER_PORT}" #:8083

adapters:
  r2dbc:
    host: "${DB_HOST}" #:localhost
    port: "${DB_PORT}" #:5432
    database: "${DB_NAME}" #:solicitud
    schema: "${DB_SCHEMA}" #:public
    username: "${DB_USER}" #:creditUserData
    password: "${DB_PASS}" #:za4iLVvR8qVq4yQv

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}" # :localhost   :5432  :solicitud
    user: "${DB_USER}" #:creditUserData
    password: "${DB_PASS}" #:za4iLVvR8qVq4yQv
    schemas: "${DB_SCHEMA}" #:public
    default-schema: "${DB_SCHEMA}" #:public
    locations: "classpath:db/migration"

  application:
    name: "CrediYa_Solicitud"

  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}" #:localhost  :5432 :solicitud :public
    username: "${DB_USER}" #:creditUserData
    password: "${DB_PASS}" #:za4iLVvR8qVq4yQv

  devtools:
    add-properties: false

  h2:
    console:
      enabled: true
      path: "/h2"

  #profiles:
    #include: null

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

  health:
    circuitbreakers:
      enabled: true

cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}" #:http://localhost:4200,http://localhost:8080,http://localhost:8083

springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true

logging:
  level:
    root: "WARN"
    co.com.crediya_solicitud.api.logger: "INFO"

routes:
  solicitud:
    base: "/api/v1/solicitud"

other:
  microservice:
    base-url: "/api/v1/usuarios/document"

adapter:
  sqs:
    region: "us-east-2"
    notifier:
      queue-url: https://sqs.us-east-2.amazonaws.com/657258631869/SQS_Notificaciones
    callback:
      queue-url: https://sqs.us-east-2.amazonaws.com/657258631869/SQS_Callback
      wait-time-seconds: 20
      max-messages: 10


  restconsumer:
    url: "${RESTCONSUMER_URL}" #:http://localhost:8080
    timeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"


# ========= Documento perfil API =========
---
spring:
  config:
    activate:
      on-profile: api
  main:
    web-application-type: reactive

# Aquí vinculamos el sender a la cola de NOTIFICACIONES
adapter:
  sqs:
    notifier:
      queue-url: "https://sqs.us-east-2.amazonaws.com/657258631869/SQS_Notificaciones"

# ========= Documento perfil WORKER =========
---
spring:
  config:
    activate:
      on-profile: worker
  main:
    web-application-type: none

# Aquí el worker escucha la cola de CALLBACK
adapter:
  sqs:
    callback:
      queue-url: "https://sqs.us-east-2.amazonaws.com/657258631869/SQS_Callback"
      # Si luego creas otra @ConfigurationProperties para consumo, podrás agregar:
      wait-time-seconds: 20
      max-messages: 10